spring.application.name=habittracker

spring.datasource.url=jdbc:postgresql://dpg-d7fi9pl8nd3s73dtnegg-a.virginia-postgres.render.com:5432/habitdb_r2zs
spring.datasource.username=habitdb_r2zs_user
spring.datasource.password=5IXHebzs6G1guTDeulcWXBtNBFt2dz6M

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}